name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests toml
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Run tests
        run: |
          python tests/url_status_code.py
